// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"encoding/json"
)

type Book struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Image       *string         `json:"image"`
	Description json.RawMessage `json:"description"`
}

type FavBook struct {
	BookID string `json:"book_id"`
	UserID string `json:"user_id"`
}

type User struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
}
